api-gateway:
  property: Api-gateway profile dev

spring:
  cloud:
    gateway:
      default-filters:

      routes:
        - id: oauth2-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/oauth2/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
        - id: shopping-service
          uri: lb://shopping-service
          predicates:
            - Path=/api/v1/shopping/**
