api-gateway:
  property: Api-gateway profile dev

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
            - Path=/api/v1/shopping/**
            - Path=/api/v1/products/**