api-gateway:
  property: Api-gateway profile dev

scheme: http

auth0-issuer: https://dev-4nl5k5ui2y3z081n.us.auth0.com/
auth0-client-id: eOSlbhL4uQhWIia3I6yXNqGhbxv7iehq
auth0-secret: gyhuo0QyAHwDe6VeVa6bAabSDwoqBKknf7VU0kf91a-GGHfQKvg9LsbQO516_0LU

gateway-uri: ${scheme}://localhost:${server.port}
react-uri: ${scheme}://localhost:5173/

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - SaveSession
      routes:
        - id: home
          uri: ${gateway-uri}
          predicates:
            - Path=/
          filters:
            - RedirectTo=301,${gateway-uri}
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - TokenRelay=
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
          filters:
            - TokenRelay=
        - id: shopping-service
          uri: lb://shopping-service
          predicates:
            - Path=/api/v1/shopping/**
          filters:
            - TokenRelay=
        - id: ui
          uri: ${react-uri}
          predicates:
            - Path=/