user-service:
  property: User-service profile dev

spring:
  datasource:
    username: carlos
    password: admin
    url: jdbc:mysql://localhost:3306/user-service?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update