user-service:
  property: User-service profile dev

spring:
  r2dbc:
    username: carlos
    password: admin
    url: r2dbc:mysql://localhost:3306/user-service?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
