user-service:
  property: User-service profile dev

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/microservices-realm
  datasource:
    username: carlos
    password: admin
    url: jdbc:mysql://localhost:3306/user-service?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update


management:
  endpoints:
    web:
      exposure:
        include: info, health, env